[package]
name = "util-linux"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.0.22"
term_size = "0.3.2"
pancurses = "0.17"
winconsole = "0.11"
rustyline = "10.0.0"